#lang racket
(require "AlgoritmoCodicioso.rkt")

(println "-----crear matriz-----")
(define mat (buildMatrix 4 4))
(printMat mat)
(println "-----cambiar el valor de una matriz-----")
(set! mat (setValToPos mat 0 0 1))
(set! mat (setValToPos mat 0 1 1))
(set! mat (setValToPos mat 0 2 1))
(set! mat (setValToPos mat 0 3 1))
(set! mat (setValToPos mat 1 0 1))
(set! mat (setValToPos mat 1 1 1))
(set! mat (setValToPos mat 1 2 1))
(set! mat (setValToPos mat 1 3 1))
(set! mat (setValToPos mat 2 0 1))
(set! mat (setValToPos mat 2 1 2))
(set! mat (setValToPos mat 2 2 2))
(set! mat (setValToPos mat 2 3 1))
(set! mat (setValToPos mat 3 0 1))
(set! mat (setValToPos mat 3 1 1))
(set! mat (setValToPos mat 3 2 1))
(set! mat (setValToPos mat 3 3 1))
(printMat mat)
(displayln (seleccion mat))
